### ISSUE TITLE
how to configure dnsvizwww

### ISSUE THREAD

**Issue by teadur** [dnsviz/dnsvizwww#1]
Starting dnsvizwww  with gunicorn wsgi:app halts in error : 

/usr/local/lib/python2.7/dist-packages/dnsvizwww$ [2017-03-07 13:30:50 +0000] [12830] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 384, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/dnsvizwww/wsgi.py", line 24, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings
[2017-03-07 13:30:50 +0000] [12830] [INFO] Worker exiting (pid: 12830)

How should i configure dnsvizwww so that it settings is provided ?

**Comment by cdeccio** [comment]
Thanks for the question.  While most of the code for the Web-based dnsviz.net is made available in the dnsvizwww repository, it has never been developed as a package for easy installation--and probably won't be.

A better approach that I have envisioned is to develop a simple, Web-based front-end to the DNSViz library (i.e., the dnsviz repository) and include it with the code (e.g., in the contrib/ directory).
